sudo: required
services:
  - docker

before_install:
  - docker build -t henrihila/react-test -f ./client/Dockerfile.dev ./client
  # - docker build myotherproject

script:
  - docker run henrihila/react-test npm test -- --coverage
  # - docker run myotherproject runmytests

after_success:
  - docker build -t henrihila/multi-client ./client
  - docker build -t henrihila/multi-nginx ./ngix
  - docker build -t henrihila/multi-server ./server
  - docker build -t henrihila/multi-worker ./worker

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take above production images and push them to docker hub
  - docker push henrihila/multi-client
  - docker push henrihila/multi-nginx
  - docker push henrihila/multi-server
  - docker push henrihila/multi-worker