sudo: required
services:
  - docker

before_install:
  - docker build -t henrihila/react-test -f ./client/Dockerfile.dev ./client
  # - docker build myotherproject

script:
  - docker run henrihila/react-test npm test -- --coverage
  # - docker run myotherproject runmytests

after_success:
  - docker build -t henrihila/multi-client ./client
  - docker build -t henrihila/multi-nginx ./ngix
  - docker build -t henrihila/multi-server ./server
  - docker build -t henrihila/multi-worker ./worker